name = "ThickNumbers"
uuid = "b57aa878-5b76-4266-befc-f8e007760995"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[extensions]
ThickNumbersForwardDiffExt = "ForwardDiff"

[compat]
julia = "1.9"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ForwardDiff", "Test"]
